### PR TITLE
Add a notebook post about hvplot and dataframes to the labs blog.

### PR DESCRIPTION
**Pull request by tonyfast**
Hey there,

I was hoping y'all could consider this post for the Labs blog.

Y'all can preview the post independent of nikola here.

https://bl.ocks.org/tonyfast/raw/e8d0444e2a24e7ccef0cbb8fd496facb/

It describes how hvplot works generally with differents, and removes minimizes the need for
bespoke visualization.

I also configured notebook to only render output which maybe could be a problem for someone.  I checked that this was the first notebook post so I'll see what y'all think.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @tonyfast!

There's some issues with rendering, you can see a preview at https://253-179573943-gh.circle-artifacts.com/0/output/blog/2020/02/visualizing-dataframe-objects-with-hvplot/index.html 

- easy fix: remove the title in the notebook, since it's now rendered twice
- perhaps a bit more involved: most images give errors (message: `bokeh.core.validation.check - ERROR - E-1006 (NON_MATCHING_DATA_SOURCES_ON_LEGEND_ITEM_RENDERERS): LegendItem.label is a field, but renderer data sources don't match: LegendItem(id='1077', ...)`)

**Comment by rgommers** [comment]
@tonyfast any plans to get back to this? not super urgent, but would be nice to have in 1-2 weeks

**Comment by tonyfast** [comment]
I finally got to some updates.  I couldn't figure where that stupid error message was coming from. Anyway. happy to make changes.

**Comment by rgommers** [comment]
Thanks @tonyfast. I asked on the Labs blog for help with review, maybe someone else will spot the issue with the Bokeh warnings.

**Comment by tonyfast** [comment]
Oh, I was able to get them to go away. The updated version does not have them. Thanks for grabbing a reviewer.

**Comment by dhavide** [comment]
Hey @tonyfast   Here is some feedback about your draft blog post for the Quansight Labs blog. Sorry for the delay. If you have a more recent draft, let me know and I'll look at that (I am still seeing errors for the images. Is there a way I can see what those are?).

+ Introduction: The introduction needs to be fleshed out. What does this post cover? Who is it aimed at? I am unclear on who the intended audience is (i.e., what you're expecting that they'll know already). 

+ The definition of the function `ohlc` should be moved later, after you have shown the dataframe to provide a context in which the plotting makes sense.

+ Is the intent that this is meant to be an executable document or a static post? I can't tell in its current format; I suppose this makes a difference in how the narrative is phrased.

+ This would be easier to follow with some rearranging of the paragraphs (and with more explanatory text filling in details). For instance, consider building the post around section headers something like this:

   + Introduction
   + The form of a dataframe
   + Visualizing an OHLC dataframe
   + Extending dataframe visualizations: Dask & streamz

+  This sentence doesn't make sense. I think it's a copy-paste error in which two sentences were merged.
   
>   When we approach visualization in A useful practice for composing dataframes are visual objects is to place the independent variables along the index and the dependent variables along the columns.

**Comment by tonyfast** [comment]
i dont think im going to finish this. ill work on a hvplot ibis post when i clear that pr

**Pull request closed without merging**
