### PR TITLE
Added new logo and colors according to branding guide.

### PR DESCRIPTION
**Pull request by melissawm**
This is still WIP as the sponsors image needs to be updated with the new Quansight logo, and there may be missing elements to change (such as the font family).

### CODE REVIEW

**Comment by rgommers** [comment]
The colors on quansight.com look much darker:

image

Netlify preview of this PR:

image

**Comment by melissawm** [comment]
I just followed the colors on the branding guide, but maybe I missed something in the CSS. I'll investigate, thanks for pointing it out!

**Comment by rgommers** [comment]
Colors are tricky, maybe it's a color space thing or something.

**Comment by rgommers** [comment]
Ah, that's the simpler explanation:)

**Review by rgommers — APPROVED** [review]
Let's get this in, sorry for the delay Melissa.

**Pull request merged**
