### PR TITLE
JupyterLab accessibility post 2

### PR DESCRIPTION
**Pull request by isabela-pf**
Here's the first sequel for the JupyterLab accessibility post from March. Thanks in advance for the feedback! 🌻

### CODE REVIEW

**Comment by trallard** [comment]
Task linked: [CU-gx3cvr Jupyter accessibility](https://app.clickup.com/t/gx3cvr)

**Review by rgommers — APPROVED** [review]
This is a beautifully written post @isabela-pf! Thank you. It looks good to go to me.

**Comment by trallard** [comment]
I love love love this post @isabela-pf thank you for writing this! 

I will leave it to @melissawm as our content lead to decide on publishing steps forward

**Review by trallard — APPROVED** [review]

**Comment by isabela-pf** [comment]
Hi there! Is there anything I need to do to clean this up for posting (other than vastly changing the date)?

**Comment by trallard** [comment]
I believe it all ready to go - @melissawm  do we have anything in the pipeline right now?

**Comment by rgommers** [comment]
Thanks for the ping Isabela. Let's get this published, it's a beatiful post!

**Pull request merged**
