### PR TITLE
Fix CI.

### PR DESCRIPTION
**Pull request by hameerabbasi**

### CODE REVIEW

**Comment by rgommers** [comment]
thanks! I guess that fixed the problem we saw on Aaron's PR?

**Comment by hameerabbasi** [comment]
I certainly hope so, although someone without permissions may have to check.

**Comment by rgommers** [comment]
let's see with the next PR then:)

**Comment by hameerabbasi** [comment]
Or we can merge `master` into those other PRs. :)

**Comment by rgommers** [comment]
Okay this is all good, deploy also worked as expected.

**Pull request merged**
