### PR TITLE
Katie develop 2

### PR DESCRIPTION
**Pull request by koliphan2**
Small little edits to more align with designs.

### CODE REVIEW

**Comment by rgommers** [comment]
The styling of the project names on the team page looks much nicer font/color wise, but spacing/commas are a bit off (no space before comma would look better):

image

**Comment by rgommers** [comment]
For the blog main page, the separator line between posts, title hover and going away from purple are improvements. To be the pure black for titles looks slightly harsh, would dark grey look better?

**Comment by koliphan2** [comment]
There is a subtle change for the header to see if that looks less harsh

**Comment by rgommers** [comment]
Hmm, I'm having a hard time seeing the difference, both are semi-dark purple:

image

**Comment by trallard** [comment]
This has been stale for a while so I am going to close this. Also Tony has been working on some style improvements

**Pull request closed without merging**
