### PR TITLE
Blog post for my work in September

### PR DESCRIPTION
**Pull request by asmeurer**
Will also be cross-posted to my blog. Here is how the post will look on my blog.

Please review the intro text where I talk about Quansight and Quansight Labs. https://www.asmeurer.com/blog/_quansight-labs-09-2019/posts/quansight-labs-work-update-for-september-2019/

### CODE REVIEW

**Comment by rgommers** [comment]
Looks great, thanks @asmeurer. Only two small comments:

For your own blog it says: `This post has been cross-posted on the Quansight Blog`, can you make that "Quansight Labs Blog"?

Can you insert `<!-- TEASER_END -->` above the first code snippet? That way the front page gets a "read more ..." link (see README on this repo).

**Comment by asmeurer** [comment]
Done.

**Comment by rgommers** [comment]
Thanks. Missed one more: please put your own name as author in the metadata. It now says "Quansight Labs Team" as the default.

**Comment by asmeurer** [comment]
Fixed.

**Pull request merged**
