### PR TITLE
ENH Include logo in metadata

### PR DESCRIPTION
**Pull request by thomasjpfan**
Closes https://github.com/Quansight-Labs/quansight-labs-site/issues/106

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Great, thanks Thomas! Let's give this a go:)

**Comment by rgommers** [comment]
Can't see it working yet, but I guess Twitter has an internal cache - needs a new tweet to try. _[goes off to push forward a draft blog post to have something to tweet about]_

**Comment by thomasjpfan** [comment]
I use this site for testing metatags: https://metatags.io. You can try by inserting the https://labs.quansight.org/ url.

(Looks like it is working on [twitter's validator](https://cards-dev.twitter.com/validator) as well)

**Comment by rgommers** [comment]
cool, thanks!

**Pull request merged**
