### PR TITLE
Increase the body font-size to 18px

### LINKED ISSUE #109: Font size
The font size on the site feels rather small. I would suggest bumping it from the current 14px to at least 16px, if not more.

### PR DESCRIPTION
**Pull request by asmeurer**
Fixes #109.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks Aaron. I agree that a font size bump would be good, but this seems a bit much. The code blocks in blog posts are overflowing (see, e.g., the most recent post on Traitlets).

How about trying 16px?

**Comment by asmeurer** [comment]
16 seems fine. Although note that we can also easily adjust the font-size for code blocks separately.  

Also I noticed that the h4 font-size is already 18px so we should probably increase that (even with a body font-size of 16 it is too close IMO).

**Comment by asmeurer** [comment]
These are the header font sizes

```css
h1,
.h1 {
  font-size: 36px;
}
h2,
.h2 {
  font-size: 30px;
}
h3,
.h3 {
  font-size: 24px;
}
h4,
.h4 {
  font-size: 18px;
}
h5,
.h5 {
  font-size: 14px;
}
h6,
.h6 {
  font-size: 12px;
}
```

So already h6 is smaller than body, which seems odd. This is what they look like on master

Screen Shot 2020-08-31 at 5 05 33 PM

**Comment by rgommers** [comment]
I think no one should be using h5 or h6, and probably not h4 either. Such a deep nesting doesn't make sense for a normal page or blog post.

**Comment by asmeurer** [comment]
I noticed the h4 thing because it's used in the Traitlets post.

**Comment by rgommers** [comment]
Hmm yeah, I removed some section headers there, but it was pretty aggressive in using them.

**Comment by rgommers** [comment]
@asmeurer want to rebase and update to 16px?

**Comment by asmeurer** [comment]
Well, I'm not sure how to handle the headers. I think they would need to be increased too.

**Comment by tonyfast** [comment]
Would it make more sense to REM units instead of fixed pixels?

**Comment by asmeurer** [comment]
It would be nice if someone who actually understands design and/or CSS could finish this.

**Comment by trallard** [comment]
Will close since this is already covered in #271

**Pull request closed without merging**
