### PR TITLE
add blog post with a Labs status update for April.

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by rgommers** [comment]
I plan to publish this tomorrow evening or Saturday. @skrah could you review the XND related content?

@teoliphant perhaps you want to look over the funding and "shaping Labs" sections?

**Comment by skrah** [comment]
@rgommers Thanks, looks good!   Perhaps it is worth mentioning "serializing and pickling xnd containers", which is a new feature added in April.

**Comment by rgommers** [comment]
thanks @skrah, will include that.

**Comment by rgommers** [comment]
Okay let's get this up, don't want to wait another couple of days to get this out - it's for April after all. Thanks for the feedback here and on Slack everyone! Please ping me in case any tweaks are still needed.

**Pull request merged**
