### PR TITLE
team: Add Rohit Goswami

### PR DESCRIPTION
**Pull request by HaoZeke**

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Thanks @HaoZeke!

**Comment by rgommers** [comment]
Actually, do you want to add any other projects, maybe LFortran? That's kind of in scope for Labs, and Gagan has that listed as well.

**Comment by HaoZeke** [comment]
Sure, that'd be great! I'll add it.

**Comment by HaoZeke** [comment]
Done; sorry for the delay.

**Review by rgommers — APPROVED** [review]
Thanks, LGTM now!

**Pull request merged**
