### PR TITLE
Blog post on python-moa

### PR DESCRIPTION
**Pull request by costrouc**
Python-moa blog post. Will most likely have to figure out how notebooks are converted with lektor and proper naming conventions for the post. Here is a start.

### CODE REVIEW

**Comment by rgommers** [comment]
> Will most likely have to figure out how notebooks are converted with lektor and proper naming conventions for the post

I've figured that out, will push a branch later. It's just ugly still due to CSS clashes. There are many bug reports, stuff like: https://github.com/jupyter/nbconvert/issues/226#issuecomment-179161515 (suggestion to just embed the whole `nbconvert` output in an iframe as a workaround, not great).

**Comment by rgommers** [comment]
I'm working on integrating this. I noticed that the title isn't very descriptive. @costrouc would "python-moa: a Mathematics of Arrays compiler" make sense as a title?

(note that the title goes into `contents.lr`, working on getting this up now

**Comment by costrouc** [comment]
Thanks! Yes a more descriptive title is needed. When I talked with Brendan we settled on "MOA: a theory for composable and verifiable tensor computations"  but either is fine with me!

**Comment by rgommers** [comment]
That sounds good too. It's your post, you choose:)

**Comment by costrouc** [comment]
Added author and title to post

**Comment by rgommers** [comment]
Okay continued in gh-9. It's good to go there. Thanks Chris!

**Comment by rgommers** [comment]
It's up: https://labs.quansight.org/blog/2019/04/python-moa-tensor-compiler/

**Pull request closed without merging**
