### PR TITLE
add blog post for `pytest-pytorch`

### PR DESCRIPTION
**Pull request by pmeier**
This is the official introduction of [`pytest-pytorch`](https://github.com/Quansight/pytest-pytorch) that will be linked from the PyTorch developer wiki.

### CODE REVIEW

**Comment by pmeier** [comment]
@mruberry If you are happy with the post please "sign off on it". If it is merged I'll update the developer wiki and prepare a post in the slack announcements channel.

**Comment by mruberry** [comment]
I was sold in the first section and I appreciated the technical discussion that followed. LGTM!

**Comment by pmeier** [comment]
Thanks for the improvements @rgommers!

**Review by rgommers — APPROVED** [review]
LGTM too, thanks @pmeier! And thanks @mruberry for reviewing.

I just pushed a change to make the teaser a little shorter so it didn't take up the whole front page, and changed the publication date. Other than that the structure flows well, and I didn't have even a typo to fix. High quality post, much appreciated!

**Comment by rgommers** [comment]
Live now at https://labs.quansight.org/blog/2021/06/pytest-pytorch/

**Pull request merged**
