### PR TITLE
Blog post: PyTorch-Ignite: training and evaluating neural networks flexibly and transparently

### PR DESCRIPTION
**Pull request by vfdev-5**
Introductory post about PyTorch-Ignite

TODO:
- [x] Open for everyone Google Colab link
- [x] TOC
- [x] Make smaller "Pure PyTorch vs PyTorch-Ignite" table

### CODE REVIEW

**Comment by vfdev-5** [comment]
@rgommers could you please review the post ? Thanks !

**Comment by rgommers** [comment]
Thanks @vfdev-5! I did a quick review - this looks great, it's a well-structured story.

Suggestion on the author affiliations: 

> `Authors: Victor Fomin (Quansight, FR), Sylvain Desroziers (IFPEN, FR) `

I'd write this as `Authors: Victor Fomin (Quansight), Sylvain Desroziers (IFPEN, France)`

GitHub refuses to show the diff for a notebook this large; I may push some minor textual fixes before publishing.

**Comment by vfdev-5** [comment]
@rgommers sounds good ! I'll change the author affiliations as you suggested

**Comment by vfdev-5** [comment]
@rgommers I updated the article as suggested by your review and IFPEN's one :
- replaced intro image (IFPEN's comment)
- added Labs/IFPEN logos and their presentations with a sentence about a "support" for the project.

Could you please review it. Thanks !

**Comment by rgommers** [comment]
Thanks @vfdev-5, this looks great. I pushed some textual fixes in the last commit, pretty much all are trivial but please check. A couple of other comments:

Are the `evaluator.run` lines commented out on purpose here (as well as further down)?

image

If so, you may want to add a comment behind it like `# commented out for demo purposes` or some such thing, because it looks confusing now.


FYI, there's no list of handlers at https://pytorch.org/ignite/contrib/handlers.html#ignite-contrib-handlers, even though the blog post says there is one - may need a doc fix PR?

Other comment unrelated to the blog post: the split between `ignite.xxx` and `ignite.contrib.xxx` does not look very nice, that's just splitting functionality over two places - perhaps best to get rid of that in the long term.

**Comment by vfdev-5** [comment]
Ralf, thanks a lot for fixing the text ! Me and Sylvain, we have to backprop for a few steps in order to improve our skills in english :) 

> If so, you may want to add a comment behind it like # commented out for demo purposes or some such thing, because it looks confusing now.

Thanks, yes, it makes sense to add `# commented out for demo purposes` as it is exactly put for demo purposes (there is no evaluator defined in the code snippet).

> FYI, there's no list of handlers at https://pytorch.org/ignite/contrib/handlers.html#ignite-contrib-handlers, even though the blog post says there is one - may need a doc fix PR?

That's true that there is no list similar to other links. On the right there sections that group handlers by type.

> Other comment unrelated to the blog post: the split between ignite.xxx and ignite.contrib.xxx does not look very nice, that's just splitting functionality over two places - perhaps best to get rid of that in the long term.

This is a good point. In the begining we wanted to split as in `contrib` modules can require other additional dependencies. We have to think about that...

**Comment by rgommers** [comment]
Great, the build is broken - apparently because a dependency of `nikola` released a version incompatible with nikola 8.0.4. And no idea which one, there's a lot of them. This is probably my punishment for bring up specifying `<= max_version` dependency ranges in the last hour.

**Comment by rgommers** [comment]
All green again, in it goes. Thanks @vfdev-5!

**Comment by rgommers** [comment]
And it's up: https://labs.quansight.org/blog/2020/09/pytorch-ignite/

**Comment by vfdev-5** [comment]
Thanks @rgommers !

Btw, just found that there is a bad link to "Distributed and XLA device support" section when "XLA devices" was changed to "XLA device". I'll send another PR to fix it.

**Pull request merged**
