### PR TITLE
Tries to fix CircleCI build 

### PR DESCRIPTION
**Pull request by melissawm**
Changes pip upgrade strategy to solve nikola build problem on CircleCI.

edit: still trying to figure out the right solution to pass both CircleCI and Netlify.

### CODE REVIEW

**Comment by melissawm** [comment]
@rgommers Looks like pinning Python=3.7 to CircleCI works - this makes it compatible to the Netlify Python version.

**Comment by rgommers** [comment]
Awesome, thanks Melissa!

**Comment by rgommers** [comment]
That makes perfect sense - everything is pinned in `requirements.txt`, but can't pin the Python version there:(

**Comment by rgommers** [comment]
There are two jobs; the deploy one on merge to master needed the same fix. Follow up in gh-139.

**Pull request merged**
