### PR TITLE
Blog Post: Designing with and for developers

### PR DESCRIPTION
**Pull request by isabela-pf**

### CODE REVIEW

**Comment by rgommers** [comment]
Nice post, I like where this is going, thanks @isabela-pf.

I suspect quite a few readers may still wonder what that design process is actually like then. An example could help there. Not sure if you planned to add one here, or leave that to a follow up post (it could get large quickly with screenshots). I'm happy either way.

**Comment by isabela-pf** [comment]
I've revised based on the above feedback and comments from @tonyfast. I reordered how everything is presented and made it clear that I won't be discussing design process much because when I started to write that it became longer and felt less focused to me (probably worthy of its own post if that is interesting).

**Comment by rgommers** [comment]
> I've revised based on the above feedback and comments from @tonyfast. I reordered how everything is presented and made it clear that I won't be discussing design process much because when I started to write that it became longer and felt less focused to me (probably worthy of its own post if that is interesting).

Seems like a good decision to me. The separate post does sound quite interesting.

> Also, I can move this post to the appropriate August folder if needed. I didn't think of it ahead of time.

Thanks, that'd be helpful. Also, if you think it's ready you can edit the PR title to remove `WIP` (I often ignore WIP PRs if I'm busy).

**Comment by isabela-pf** [comment]
I think I made all the appropriate changes. Thanks again for the review!

**Comment by rgommers** [comment]
Looks great, thanks @isabela-pf! I reformatted the file, updated metadata, and merged. Should be live in a minute

**Pull request merged**
