### PR TITLE
PR: Initial team page

### LINKED ISSUE #56: Team page layout & contents
The 2-D grid that was a previous version of the Projects page would be nice for the Team page. I'm thinking for each listed person there should be: full name, a picture (or GitHub logo), and names of projects. Perhaps project names should say "maintainer" or "contributor".

The main criterion to be listed is that you should be a maintainer or contributor (ongoing contributions, not a one-off PR) to a project listed on the Projects page. Also, if you want to be listed on this page as part of the Labs Team, there's an expectation of making contributions to help shape Labs - this could be help maintaining the website, writing a blog post once every couple of months, or other equivalent/useful activities (more detail TBD). This is a sort of "co-op model" (thanks @saulshanabrook for that suggestion).

People to be listed (note, this is 1-2 months old, if someone is missing please comment or ping me on Slack):

Ralf Gommers
Saul Shanabrook
Hameer Abbasi
Carlos Cordoba 
Gonzalo Peña-Castellanos
Edgar Margffoy
Stephannie Jiménez Gacha
Daniel Althviz
Melissa Weber Mendonça
Mars Lee
Yuvi Panda
Anthony Scopatz 
Athan Reines
Aaron Meurer
Chris Ostrouchov
James Bourbeau
Ivan Ogasawara
Peter Bell
Pearu Peterson
Sameer Deshmukh
Nathan Goldbaum
Guilherme Leobas
Anirrudh Krishnan
Marc Garcia

### PR DESCRIPTION
**Pull request by dalthviz**
Part of #56 

Implements the layout for the Team page. Missing full contents addition.

A preview:

image

### CODE REVIEW

**Comment by dalthviz** [comment]
@rgommers I was thinking in adding a link to the GitHub profile too, I will do that then (adding a link in the name). Although, If more than the GitHub profile link is needed (like a link for Twitter, LinkedIn or other social media), probably adding an icon per link could be better. something like: 

image


About the image extension, any format can be used (`svg`, `png`, `jpeg`, etc). The content I added here is kind of just a placeholder to check the layout (I took the images from bamboo but I didn't check the extension, maybe since I copied them using drag&drop they ended up with such a weird extension 😅 ).

**Comment by rgommers** [comment]
I'm thinking just GitHub and not Twitter, because (a) not everyone has a Twitter or LinkedIn account so it may not look uniform, and (b) Twitter accounts may not be programming/work related.

**Comment by rgommers** [comment]
The GitHub icon may still be a nice touch. If it's not too hard to do, it would look cooler

**Comment by rgommers** [comment]
Yay an icon:) Should it be purple or the standard grey? It may be more recognizable if grey.

**Comment by goanpeca** [comment]
Looking sweet! :-)

**Comment by koliphan2** [comment]
With the team page, do we want it to mimic the look of the Quansight Team page?
Screen Shot 2020-03-18 at 2 24 44 PM
Square images, gaps both horizontal and vertical between people, hovering brings up individual info, etc... Instead of role/rank, it could be which projects they've worked on

**Comment by rgommers** [comment]
I'm happy to see more styling - a little more color on the whole site would be nice. The round photos I quite like though personally, more so than square. On the other hand, the black and white of quansight.com is nice - but we don't have those photos right now. I'll follow up on the Slack channel.

The priority for this PR is to add more people I think - this was just six, not the whole list. @dalthviz could you send a follow-up PR for that?

**Pull request merged**
