### PR TITLE
Jupyterlab Collaboration

### PR DESCRIPTION
**Pull request by saulshanabrook**
Put down some thoughts here. Will re-read tomorrow and see what seems useful here.

### CODE REVIEW

**Comment by saulshanabrook** [comment]
Closing for now, since the kite work is paused.

**Comment by saulshanabrook** [comment]
Reopening

**Comment by saulshanabrook** [comment]
Notes from talking with Athan:



DE Shaw:

From my level, opportunity to learn from industry, how to translate learnings from de shaw environment, to rolling out improvements inside JupyterLab.

What are the user needs inside large scale deployments that are driving improvements in JupyterLab ecosystem?

Kite:

Companies trying  to leverage JLab as marketing, as an application. Quansight acts a bridge to reach target audience. 


Two sides, users, and companies and open source brings them together, how that exerts pressure on open.

---

What values does OS promote?

What does it allow? People who like open source to support themselves to do that.

Bringing sustainability to ecosystem in terms of developer livelihood.

Personal aspect: support people doing what they like to do.

Who cares if open source is supported?

Stallman: Inherit value in openness and transparency in the software that we build. 

Tim berners lee: View source in the browser, every user should be empowered to inspect underlying code.

Gives ability to individuals outside corporate institutions to provide quality control on products they use.

To increase competition, and user rights. 

---

Another angle: open source software isn't valuable, it's the data you use with it.

---

Or how do we talk about the process itself as valuable? Are the values different then in a corporate setting?

Is there something inherently unique about the values we craft the software, just a different scale of collaboration.

Or can we make the parallel to the scientific environment? That we are collectively looking for some truth in the world? Software that is not driven by the bottom line, but by exploration and an opportunity to reframe and re-evaluate the problems of the world.

There is a certain notion of freedom, that you don't get in the corporate environment. Creativity, exploration.

Iterating towards a higher goal of pursueing truth?

Companies are allowing developers to be "aristocratic scientists" instead of just their bottom lines.

So there is a tradeoff between the large investment and a quick fix. Doing things the "right way."

Better for companies in the long term, even if its not in the short term. Introducing friction and changes priorities of companies. Engaging stakeholders, and waiting for them, introduces friction. This friction forces companies to make choices that are more long term focus, and focuses unfettered creative on real need.  

What does open source add to corporate America? A chance for them to put money into something they wouldn't do themselves, because it's too slow and weird and creative, but will help everyone long term.

Trying to understand dynamic and what value it brings to the table. The dialectic between those abiding the profit maximizing principles vs people working towards the greater good or some creative process, that this is where the value is, as opposed to older OS principles about inherit good of openness in itself.

**Comment by rgommers** [comment]
Looks promising @saulshanabrook. Let me know if/when you want me to have a closer look.

**Comment by rgommers** [comment]
This is reasonably far along but almost a year old now. Maybe still useful as a case study? @ericdatakelly do you still have a use for this? If so can you link it from your tracking repo? I'd like to close this PR.

**Comment by ericdatakelly** [comment]
> This is reasonably far along but almost a year old now. Maybe still useful as a case study? @ericdatakelly do you still have a use for this? If so can you link it from your tracking repo? I'd like to close this PR.

I'll discuss it with the Jupyter folks.  I have it tracked on the Quansight repo so feel free to close this PR.

**Pull request closed without merging**
