### PR TITLE
Quantile Regression post

### PR DESCRIPTION
**Pull request by cgarciae**
Hey! I made this article about Quantile Regression a month ago and posted it on my personal HackMD, got about 3K views. I think this would be very good material for the Quansight Blog.

I use some latex formulas, do we support rendering MathJax?

## Text styling

- [x] The blog is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [x] If there are headers, they use the proper header tags in order to do so (with only one level-one header).
- [x] All links describe where they link to (for example, check the [Quansight labs website](https://labs.quansight.org/)).
- [x] Any kind of styling that the author uses (for example, bold for emphasis) is consistent throughout the blog.

## Non-text contents

- [x] All content is represented as text (for example, images need alt text and videos need captions or descriptive transcripts).
- [x] If there are emojis, there are not more than three in a row.
- [x] Don't use [flashing gifs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If it were to be read as plain text, the blog still makes sense and no information is missing. (they would have to know latex if its not rendered).

### CODE REVIEW

**Comment by trallard** [comment]
HEy @cgarciae  we do support MathJax so you should be good. Some questions:

- Is this ready for review?
- have you checked with @juanis2112  re publication date and adding this to the calendar

TODO:
- this needs to be x-posted to dev.to @cgarciae  ping me for the instructions to join the org

**Comment by cgarciae** [comment]
@trallard this is ready for review. @juanis2112 told me offline she is considering to publishing it in Sep 21.

**Review by rgommers — COMMENTED** [review]
Hey Cristian, I pushed a commit to make the post render locally, some Nikola metadata was missing. I just scanned the post, so here are some high-level comments:

- It will be unclear to the reader why this blog post is here (on the Labs blog). There is no connection to Labs, or to Elegy beyond the last bullet point of the post.
- What is the main purpose of this post, and who is it aimed at? Is it a tutorial-like thing? Or a new algorithm? Or a way to tell people about Elegy? Or ....?
- The title should reflect that purpose, it's too short now.

**Comment by tonyfast** [comment]
@cgarciae you think you could address some of @rgommers comments to get this is publishable state?

**Comment by cgarciae** [comment]
Thanks @tonyfast for the ping!

@rgommers Its mostly a tutorial for data scientist about a useful but not that popular technique. Elegy and JAX are just used as tools, not the main focus in this case. You make a good point about the content regarding Labs, should I send it to Quansight's Blog instead?

**Comment by tonyfast** [comment]
> You make a good point about the content regarding Labs, should I send it to Quansight's blog instead?

@katebrack @ericdatakelly

**Comment by cgarciae** [comment]
@trallard Should I post it on dev.to regardless?

**Comment by Katebrack** [comment]
@tonyfast Thanks for sending, we can take it for Quansight. Troy and I took a quick pass and think it'd be good. I'll do a deeper read soon and talk to @ericdatakelly about adding it to the pipeline.

**Comment by ericdatakelly** [comment]
@cgarciae you implemented this in our recent client project, correct? (Let's keep the client's name private for now)  For the Quansight blog, we should be able to frame this post in that context.  It would probably only need small changes to the introduction.

**Comment by cgarciae** [comment]
@ericdatakelly yeah, I did some research on this topic to implement it for that client.
As you say, I think the introduction could be improved if we want to add some extra motivations.

**Comment by cgarciae** [comment]
@trallard working with @ericdatakelly and @Katebrack to publish it on the other blog.

**Pull request closed without merging**
